name: CI Tests

on:
  push:
    branches:
      - main
    paths:
      - "contracts/**"
      - "testcases.json"
      - "tests.mjs"

jobs:

  test-solc:
    name: Run Solidity Tests

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 20.x ]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and run Geth
        uses: ethers-io/run-geth-action@main

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
